---
name: "Build"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 23"
      uses: "actions/setup-java@v4"
      with:
        distribution: "zulu"
        java-version: "23"
        java-package: "jdk"
        cache: "maven"
    - run: "sdk env install"
    - run: "sdk env"
    - run: "mvn clean spotless:check install"
